<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TEST</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <Version>2.0.3</Version>
    <PathMap>$(MSBuildProjectDirectory)=TEST</PathMap>
    <!-- The two lines below will set the output path for the binaries -->
    <AssemblyName>TEST</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\db\CustomQuestZones\**" />
    <Content Remove="Resources\db\CustomQuestZones\**" />
    <EmbeddedResource Remove="Resources\db\CustomQuestZones\**" />
    <None Remove="Resources\db\CustomQuestZones\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.1.2" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.2" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.2" />
    <PackageReference Include="WTT-ServerCommonLib" Version="3.0.6" />
  </ItemGroup>
</Project>
